name: font_icons_github_scraper
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dart_json_mapper: ^2.1.10
  dcli: ^1.8.0
  recase: ^4.0.0
  acyclic_steps: ^0.11.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.2
  import_sorter: ^4.6.0
